"""default order

Revision ID: 0b29f7637369
Revises: 88ca16bad4c5
Create Date: 2019-01-13 19:02:33.705826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b29f7637369'
down_revision = '88ca16bad4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('default_order_desc', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'default_order_desc')
    # ### end Alembic commands ###
