"""first

Revision ID: 21c36ae5d2d4
Revises: 
Create Date: 2018-12-19 16:26:07.593690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c36ae5d2d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('access', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('list_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_access'), 'list', ['access'], unique=False)
    op.create_index(op.f('ix_list_created'), 'list', ['created'], unique=False)
    op.create_index(op.f('ix_list_last_modified'), 'list', ['last_modified'], unique=False)
    op.create_index(op.f('ix_list_list_type'), 'list', ['list_type'], unique=False)
    op.create_index(op.f('ix_list_name'), 'list', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_name'), table_name='list')
    op.drop_index(op.f('ix_list_list_type'), table_name='list')
    op.drop_index(op.f('ix_list_last_modified'), table_name='list')
    op.drop_index(op.f('ix_list_created'), table_name='list')
    op.drop_index(op.f('ix_list_access'), table_name='list')
    op.drop_table('list')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
