"""simplify biblio list

Revision ID: 288f76ed02ba
Revises: 0b29f7637369
Create Date: 2019-01-31 14:29:50.271989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288f76ed02ba'
down_revision = '0b29f7637369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_biblio_list_annotated_pdf_file', table_name='biblio_list')
    op.drop_index('ix_biblio_list_bibtex_file', table_name='biblio_list')
    op.drop_index('ix_biblio_list_link', table_name='biblio_list')
    op.drop_index('ix_biblio_list_more', table_name='biblio_list')
    op.drop_index('ix_biblio_list_pdf_file', table_name='biblio_list')
    op.drop_index('ix_biblio_list_tldr_file', table_name='biblio_list')
    op.drop_column('biblio_list', 'annotated_pdf_file')
    op.drop_column('biblio_list', 'link')
    op.drop_column('biblio_list', 'more')
    op.drop_column('biblio_list', 'pdf_file')
    op.drop_column('biblio_list', 'tldr_file')
    op.drop_column('biblio_list', 'bibtex_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biblio_list', sa.Column('bibtex_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('biblio_list', sa.Column('tldr_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('biblio_list', sa.Column('pdf_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('biblio_list', sa.Column('more', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('biblio_list', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('biblio_list', sa.Column('annotated_pdf_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_biblio_list_tldr_file', 'biblio_list', ['tldr_file'], unique=False)
    op.create_index('ix_biblio_list_pdf_file', 'biblio_list', ['pdf_file'], unique=False)
    op.create_index('ix_biblio_list_more', 'biblio_list', ['more'], unique=False)
    op.create_index('ix_biblio_list_link', 'biblio_list', ['link'], unique=False)
    op.create_index('ix_biblio_list_bibtex_file', 'biblio_list', ['bibtex_file'], unique=False)
    op.create_index('ix_biblio_list_annotated_pdf_file', 'biblio_list', ['annotated_pdf_file'], unique=False)
    # ### end Alembic commands ###
