"""adding list id in list entry tables

Revision ID: 3636037afdbc
Revises: 0fb5398902fd
Create Date: 2019-01-09 13:14:03.044286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3636037afdbc'
down_revision = '0fb5398902fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biblio_list', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_biblio_list_list_id'), 'biblio_list', ['list_id'], unique=False)
    op.create_foreign_key(None, 'biblio_list', 'list', ['list_id'], ['id'])
    op.add_column('default_list', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_default_list_list_id'), 'default_list', ['list_id'], unique=False)
    op.create_foreign_key(None, 'default_list', 'list', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'default_list', type_='foreignkey')
    op.drop_index(op.f('ix_default_list_list_id'), table_name='default_list')
    op.drop_column('default_list', 'list_id')
    op.drop_constraint(None, 'biblio_list', type_='foreignkey')
    op.drop_index(op.f('ix_biblio_list_list_id'), table_name='biblio_list')
    op.drop_column('biblio_list', 'list_id')
    # ### end Alembic commands ###
