"""empty message

Revision ID: 6e19f2498488
Revises: 288f76ed02ba
Create Date: 2019-05-21 17:02:35.619514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e19f2498488'
down_revision = '288f76ed02ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_access')
    # ### end Alembic commands ###
