"""?

Revision ID: aa2755f2c373
Revises: 3636037afdbc
Create Date: 2019-01-09 19:04:31.021638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2755f2c373'
down_revision = '3636037afdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblio_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('static_folder', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('pdf_file', sa.String(), nullable=True),
    sa.Column('annotated_pdf_file', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('tldr_file', sa.String(), nullable=True),
    sa.Column('bibtex_file', sa.String(), nullable=True),
    sa.Column('bibtex_content', sa.String(), nullable=True),
    sa.Column('more', sa.Boolean(), nullable=True),
    sa.Column('clarity_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biblio_list_annotated_pdf_file'), 'biblio_list', ['annotated_pdf_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_bibtex_content'), 'biblio_list', ['bibtex_content'], unique=False)
    op.create_index(op.f('ix_biblio_list_bibtex_file'), 'biblio_list', ['bibtex_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_content'), 'biblio_list', ['content'], unique=False)
    op.create_index(op.f('ix_biblio_list_created'), 'biblio_list', ['created'], unique=False)
    op.create_index(op.f('ix_biblio_list_last_modified'), 'biblio_list', ['last_modified'], unique=False)
    op.create_index(op.f('ix_biblio_list_link'), 'biblio_list', ['link'], unique=False)
    op.create_index(op.f('ix_biblio_list_list_id'), 'biblio_list', ['list_id'], unique=False)
    op.create_index(op.f('ix_biblio_list_more'), 'biblio_list', ['more'], unique=False)
    op.create_index(op.f('ix_biblio_list_pdf_file'), 'biblio_list', ['pdf_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_static_folder'), 'biblio_list', ['static_folder'], unique=True)
    op.create_index(op.f('ix_biblio_list_title'), 'biblio_list', ['title'], unique=False)
    op.create_index(op.f('ix_biblio_list_tldr_file'), 'biblio_list', ['tldr_file'], unique=False)
    op.create_table('default_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('static_folder', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_list_content'), 'default_list', ['content'], unique=False)
    op.create_index(op.f('ix_default_list_created'), 'default_list', ['created'], unique=False)
    op.create_index(op.f('ix_default_list_day'), 'default_list', ['day'], unique=False)
    op.create_index(op.f('ix_default_list_last_modified'), 'default_list', ['last_modified'], unique=False)
    op.create_index(op.f('ix_default_list_list_id'), 'default_list', ['list_id'], unique=False)
    op.create_index(op.f('ix_default_list_month'), 'default_list', ['month'], unique=False)
    op.create_index(op.f('ix_default_list_static_folder'), 'default_list', ['static_folder'], unique=True)
    op.create_index(op.f('ix_default_list_title'), 'default_list', ['title'], unique=False)
    op.create_index(op.f('ix_default_list_year'), 'default_list', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_default_list_year'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_title'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_static_folder'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_month'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_list_id'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_last_modified'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_day'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_created'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_content'), table_name='default_list')
    op.drop_table('default_list')
    op.drop_index(op.f('ix_biblio_list_tldr_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_title'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_static_folder'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_pdf_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_more'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_list_id'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_link'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_last_modified'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_created'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_content'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_bibtex_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_bibtex_content'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_annotated_pdf_file'), table_name='biblio_list')
    op.drop_table('biblio_list')
    # ### end Alembic commands ###
