"""list types new

Revision ID: bf7b0900bb87
Revises: f747efbde4ec
Create Date: 2018-12-20 13:47:21.173046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7b0900bb87'
down_revision = 'f747efbde4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblio_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('static_folder', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('pdf_file', sa.String(), nullable=True),
    sa.Column('annotated_pdf_file', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('tldr_file', sa.String(), nullable=True),
    sa.Column('bibtex_file', sa.String(), nullable=True),
    sa.Column('bibtex_content', sa.String(), nullable=True),
    sa.Column('more', sa.Boolean(), nullable=True),
    sa.Column('clarity_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'month', 'day')
    )
    op.create_index(op.f('ix_biblio_list_annotated_pdf_file'), 'biblio_list', ['annotated_pdf_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_bibtex_content'), 'biblio_list', ['bibtex_content'], unique=False)
    op.create_index(op.f('ix_biblio_list_bibtex_file'), 'biblio_list', ['bibtex_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_content'), 'biblio_list', ['content'], unique=False)
    op.create_index(op.f('ix_biblio_list_created'), 'biblio_list', ['created'], unique=False)
    op.create_index(op.f('ix_biblio_list_last_modified'), 'biblio_list', ['last_modified'], unique=False)
    op.create_index(op.f('ix_biblio_list_link'), 'biblio_list', ['link'], unique=False)
    op.create_index(op.f('ix_biblio_list_more'), 'biblio_list', ['more'], unique=False)
    op.create_index(op.f('ix_biblio_list_pdf_file'), 'biblio_list', ['pdf_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_static_folder'), 'biblio_list', ['static_folder'], unique=True)
    op.create_index(op.f('ix_biblio_list_title'), 'biblio_list', ['title'], unique=False)
    op.create_index(op.f('ix_biblio_list_tldr_file'), 'biblio_list', ['tldr_file'], unique=False)
    op.create_table('default_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('static_folder', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'month', 'day')
    )
    op.create_index(op.f('ix_default_list_content'), 'default_list', ['content'], unique=False)
    op.create_index(op.f('ix_default_list_created'), 'default_list', ['created'], unique=False)
    op.create_index(op.f('ix_default_list_last_modified'), 'default_list', ['last_modified'], unique=False)
    op.create_index(op.f('ix_default_list_static_folder'), 'default_list', ['static_folder'], unique=True)
    op.create_index(op.f('ix_default_list_title'), 'default_list', ['title'], unique=False)
    op.create_index(op.f('ix_list_all_read'), 'list', ['all_read'], unique=False)
    op.create_index(op.f('ix_list_all_write'), 'list', ['all_write'], unique=False)
    op.create_index(op.f('ix_list_type_id'), 'list_type', ['id'], unique=False)
    op.create_index(op.f('ix_list_type_name'), 'list_type', ['name'], unique=True)
    op.create_index(op.f('ix_list_type_template'), 'list_type', ['template'], unique=False)
    op.drop_constraint('list_type_name_key', 'list_type', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('list_type_name_key', 'list_type', ['name'])
    op.drop_index(op.f('ix_list_type_template'), table_name='list_type')
    op.drop_index(op.f('ix_list_type_name'), table_name='list_type')
    op.drop_index(op.f('ix_list_type_id'), table_name='list_type')
    op.drop_index(op.f('ix_list_all_write'), table_name='list')
    op.drop_index(op.f('ix_list_all_read'), table_name='list')
    op.drop_index(op.f('ix_default_list_title'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_static_folder'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_last_modified'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_created'), table_name='default_list')
    op.drop_index(op.f('ix_default_list_content'), table_name='default_list')
    op.drop_table('default_list')
    op.drop_index(op.f('ix_biblio_list_tldr_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_title'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_static_folder'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_pdf_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_more'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_link'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_last_modified'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_created'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_content'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_bibtex_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_bibtex_content'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_annotated_pdf_file'), table_name='biblio_list')
    op.drop_table('biblio_list')
    # ### end Alembic commands ###
