"""all read write

Revision ID: e03a1f8c1a3e
Revises: fcf4875708f4
Create Date: 2018-12-20 12:47:04.423569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03a1f8c1a3e'
down_revision = 'fcf4875708f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('all_read', sa.Boolean(), nullable=True))
    op.add_column('list', sa.Column('all_write', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'all_write')
    op.drop_column('list', 'all_read')
    # ### end Alembic commands ###
