"""biblio-list

Revision ID: f747efbde4ec
Revises: 11c9bf76bd37
Create Date: 2018-12-20 13:34:33.333132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f747efbde4ec'
down_revision = '11c9bf76bd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblio_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('static_folder', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('pdf_file', sa.String(), nullable=True),
    sa.Column('annotated_pdf_file', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('tldr_file', sa.String(), nullable=True),
    sa.Column('bibtex_file', sa.String(), nullable=True),
    sa.Column('bibtex_content', sa.String(), nullable=True),
    sa.Column('more', sa.Boolean(), nullable=True),
    sa.Column('clarity_level', sa.Enum('NotRead', 'NotClear', 'Ok', name='paperclaritylevel'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'month', 'day')
    )
    op.create_index(op.f('ix_biblio_list_annotated_pdf_file'), 'biblio_list', ['annotated_pdf_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_bibtex_content'), 'biblio_list', ['bibtex_content'], unique=False)
    op.create_index(op.f('ix_biblio_list_bibtex_file'), 'biblio_list', ['bibtex_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_content'), 'biblio_list', ['content'], unique=False)
    op.create_index(op.f('ix_biblio_list_created'), 'biblio_list', ['created'], unique=False)
    op.create_index(op.f('ix_biblio_list_last_modified'), 'biblio_list', ['last_modified'], unique=False)
    op.create_index(op.f('ix_biblio_list_link'), 'biblio_list', ['link'], unique=False)
    op.create_index(op.f('ix_biblio_list_more'), 'biblio_list', ['more'], unique=False)
    op.create_index(op.f('ix_biblio_list_pdf_file'), 'biblio_list', ['pdf_file'], unique=False)
    op.create_index(op.f('ix_biblio_list_static_folder'), 'biblio_list', ['static_folder'], unique=True)
    op.create_index(op.f('ix_biblio_list_title'), 'biblio_list', ['title'], unique=False)
    op.create_index(op.f('ix_biblio_list_tldr_file'), 'biblio_list', ['tldr_file'], unique=False)
    op.drop_index('ix_default_list_annotated_pdf_file', table_name='default_list')
    op.drop_index('ix_default_list_bibtex_content', table_name='default_list')
    op.drop_index('ix_default_list_bibtex_file', table_name='default_list')
    op.drop_index('ix_default_list_link', table_name='default_list')
    op.drop_index('ix_default_list_more', table_name='default_list')
    op.drop_index('ix_default_list_pdf_file', table_name='default_list')
    op.drop_index('ix_default_list_tldr_file', table_name='default_list')
    op.drop_column('default_list', 'annotated_pdf_file')
    op.drop_column('default_list', 'link')
    op.drop_column('default_list', 'bibtex_content')
    op.drop_column('default_list', 'more')
    op.drop_column('default_list', 'pdf_file')
    op.drop_column('default_list', 'tldr_file')
    op.drop_column('default_list', 'clarity_level')
    op.drop_column('default_list', 'bibtex_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('default_list', sa.Column('bibtex_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('default_list', sa.Column('clarity_level', postgresql.ENUM('NotRead', 'NotClear', 'Ok', name='paperclaritylevel'), autoincrement=False, nullable=True))
    op.add_column('default_list', sa.Column('tldr_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('default_list', sa.Column('pdf_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('default_list', sa.Column('more', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('default_list', sa.Column('bibtex_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('default_list', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('default_list', sa.Column('annotated_pdf_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_default_list_tldr_file', 'default_list', ['tldr_file'], unique=False)
    op.create_index('ix_default_list_pdf_file', 'default_list', ['pdf_file'], unique=False)
    op.create_index('ix_default_list_more', 'default_list', ['more'], unique=False)
    op.create_index('ix_default_list_link', 'default_list', ['link'], unique=False)
    op.create_index('ix_default_list_bibtex_file', 'default_list', ['bibtex_file'], unique=False)
    op.create_index('ix_default_list_bibtex_content', 'default_list', ['bibtex_content'], unique=False)
    op.create_index('ix_default_list_annotated_pdf_file', 'default_list', ['annotated_pdf_file'], unique=False)
    op.drop_index(op.f('ix_biblio_list_tldr_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_title'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_static_folder'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_pdf_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_more'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_link'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_last_modified'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_created'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_content'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_bibtex_file'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_bibtex_content'), table_name='biblio_list')
    op.drop_index(op.f('ix_biblio_list_annotated_pdf_file'), table_name='biblio_list')
    op.drop_table('biblio_list')
    # ### end Alembic commands ###
