"""lists read write 2

Revision ID: fcf4875708f4
Revises: c39ec1b694fc
Create Date: 2018-12-19 19:13:16.535514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf4875708f4'
down_revision = 'c39ec1b694fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('read_user_list',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'list_id')
    )
    op.create_table('write_user_list',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'list_id')
    )
    op.add_column('list', sa.Column('list_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_list_list_type_id'), 'list', ['list_type_id'], unique=False)
    op.drop_index('ix_list_access', table_name='list')
    op.drop_index('ix_list_list_type', table_name='list')
    op.drop_constraint('list_owner_id_fkey', 'list', type_='foreignkey')
    op.create_foreign_key(None, 'list', 'list_type', ['list_type_id'], ['id'])
    op.drop_column('list', 'owner_id')
    op.drop_column('list', 'access')
    op.drop_column('list', 'list_type')
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    op.add_column('list', sa.Column('list_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('list', sa.Column('access', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('list', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'list', type_='foreignkey')
    op.create_foreign_key('list_owner_id_fkey', 'list', 'user', ['owner_id'], ['id'])
    op.create_index('ix_list_list_type', 'list', ['list_type'], unique=False)
    op.create_index('ix_list_access', 'list', ['access'], unique=False)
    op.drop_index(op.f('ix_list_list_type_id'), table_name='list')
    op.drop_column('list', 'list_type_id')
    op.drop_table('write_user_list')
    op.drop_table('read_user_list')
    op.drop_table('list_type')
    # ### end Alembic commands ###
